<?php

namespace GameBundle\Repository;

/**
 * MonsterRaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonsterRaceRepository extends \Doctrine\ORM\EntityRepository
{
}
