<?php

namespace GameBundle\Repository;

/**
 * MonsterTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonsterTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
