language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly


env:
  - SYMFONY_VERSION=3.0.*
  - SYMFONY_VERSION=3.1.*
  - SYMFONY_VERSION=dev-master

before_script:
  - composer install

notifications:
  email:
    - mikopet@gmail.com
