language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly

services:
  - postgresql

env:
  - SYMFONY_VERSION=3.0.*
  - SYMFONY_VERSION=3.1.*
  - SYMFONY_VERSION=dev-master

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install

script: phpunit

notifications:
  email:
    - mikopet@gmail.com
