#game_monster:
#    resource: "@GameBundle/Controller/MonsterController.php"
#    type:     annotation

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

game:
    resource: "@GameBundle/Controller/"
    type:     annotation
    prefix:   /
    host:     game.fairiesandtales.com

web:
    resource: "@WebBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /
