game:
    resource: "@GameBundle/Controller/"
    type:     annotation
    prefix:   /
    host:     game.fairiesandtales.com

web:
    resource: "@WebBundle/Controller/"
    type:     annotation
    prefix:   /
